// 월간계획 mock 데이터

import type { MonthlyPlan } from "./types";

/** 2026년 1~6월 일부만 채워둠 (나머지는 "draft, 슬롯만 존재" 상태) */
export const MOCK_MONTHLY_PLANS: MonthlyPlan[] = [
  {
    id: "monthly-2026-1",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 1,
    status: "done",
    weeklyGoals: [
      { weekNumber: 1, goal: "신년 인사 + 연간 목표 공유", activities: ["신년 카드 만들기", "전체 회의"] },
      { weekNumber: 2, goal: "심리 안정 프로그램 안정화", activities: ["소그룹 활동", "미술치료"] },
      { weekNumber: 3, goal: "학습 멘토링 시작", activities: ["1:1 멘토링", "진단 평가"] },
      { weekNumber: 4, goal: "1월 운영 회고", activities: ["월말 회의", "일지 검토"] },
    ],
    programExecutions: [
      { programId: "prog-psy-2026", weekNumber: 1, executed: true },
      { programId: "prog-psy-2026", weekNumber: 2, executed: true },
      { programId: "prog-mentor-2026", weekNumber: 3, executed: true },
      { programId: "prog-mentor-2026", weekNumber: 4, executed: true },
    ],
    dailyLogIds: [],
    evaluation: {
      progressPct: 92,
      kpiAchieved: ["심리 안정 프로그램 8회 진행", "학습 멘토링 12회 진행"],
      notes: "1월 분위기 좋음. 멘토링 참여율 평균 75%",
      evaluatedBy: "u_1",
      evaluatedAt: "2026-02-01T10:00:00Z",
    },
  },
  {
    id: "monthly-2026-2",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 2,
    status: "done",
    weeklyGoals: [
      { weekNumber: 1, goal: "겨울 활동 — 눈놀이", activities: ["실외 활동", "간식 나누기"] },
      { weekNumber: 2, goal: "멘토링 심화 — 수학 집중", activities: ["1:1 지도", "오답노트"] },
      { weekNumber: 3, goal: "지역사회 연계 — 도서관 견학", activities: ["도서관 방문", "독서 활동"] },
      { weekNumber: 4, goal: "2월 회고 + 다음 달 준비", activities: ["월말 회의"] },
    ],
    programExecutions: [
      { programId: "prog-psy-2026", weekNumber: 1, executed: true },
      { programId: "prog-mentor-2026", weekNumber: 2, executed: true },
      { programId: "prog-community-2026", weekNumber: 3, executed: true },
    ],
    dailyLogIds: [],
    evaluation: {
      progressPct: 88,
      kpiAchieved: ["도서관 연계 1회"],
      notes: "도서관 연계 첫 시도, 보호자 반응 좋음",
      evaluatedBy: "u_1",
      evaluatedAt: "2026-03-01T10:00:00Z",
    },
  },
  {
    id: "monthly-2026-3",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 3,
    status: "done",
    weeklyGoals: [
      { weekNumber: 1, goal: "봄맞이 활동", activities: ["화분 가꾸기", "산책"] },
      { weekNumber: 2, goal: "멘토링 — 학기 단원 점검", activities: ["쪽지시험", "오답 정리"] },
      { weekNumber: 3, goal: "지역사회 연계 — 소방서 견학", activities: ["견학", "안전 교육"] },
      { weekNumber: 4, goal: "3월 회고", activities: ["월말 회의"] },
    ],
    programExecutions: [
      { programId: "prog-community-2026", weekNumber: 3, executed: true },
    ],
    dailyLogIds: [],
    evaluation: {
      progressPct: 85,
      kpiAchieved: ["소방서 견학 1회", "멘토링 12회"],
      notes: "봄 활동 호응 좋음",
      evaluatedBy: "u_1",
      evaluatedAt: "2026-04-01T10:00:00Z",
    },
  },
  {
    id: "monthly-2026-4",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 4,
    status: "done",
    weeklyGoals: [
      { weekNumber: 1, goal: "멘토링 집중", activities: ["1:1"] },
      { weekNumber: 2, goal: "심리 안정 — 분노조절", activities: ["소그룹"] },
      { weekNumber: 3, goal: "지역사회 — 보건소 연계", activities: ["건강검진 연계"] },
      { weekNumber: 4, goal: "4월 회고", activities: ["월말 회의"] },
    ],
    programExecutions: [],
    dailyLogIds: [],
    evaluation: {
      progressPct: 80,
      kpiAchieved: [],
      notes: "보건소 연계 진행 중",
      evaluatedBy: "u_1",
      evaluatedAt: "2026-05-01T10:00:00Z",
    },
  },
  {
    id: "monthly-2026-5",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 5,
    status: "done",
    weeklyGoals: [],
    programExecutions: [],
    dailyLogIds: [],
    evaluation: {
      progressPct: 90,
      kpiAchieved: [],
      evaluatedBy: "u_1",
      evaluatedAt: "2026-06-01T10:00:00Z",
    },
  },
  {
    id: "monthly-2026-6",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 6,
    status: "active",
    weeklyGoals: [
      { weekNumber: 1, goal: "여름 프로그램 준비", activities: ["안전 교육", "보호자 서면 동의"] },
      { weekNumber: 2, goal: "학부모 면담", activities: ["개별 면담", "피드백"] },
      { weekNumber: 3, goal: "멘토링 중간 평가", activities: ["진도 점검"] },
      { weekNumber: 4, goal: "6월 회고", activities: ["월말 회의"] },
    ],
    programExecutions: [],
    dailyLogIds: [],
    evaluation: {
      kpiAchieved: [],
    },
  },
  {
    id: "monthly-2026-7",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 7,
    status: "draft",
    weeklyGoals: [],
    programExecutions: [],
    dailyLogIds: [],
    evaluation: { kpiAchieved: [] },
  },
  {
    id: "monthly-2026-8",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 8,
    status: "draft",
    weeklyGoals: [],
    programExecutions: [],
    dailyLogIds: [],
    evaluation: { kpiAchieved: [] },
  },
  {
    id: "monthly-2026-9",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 9,
    status: "draft",
    weeklyGoals: [],
    programExecutions: [],
    dailyLogIds: [],
    evaluation: { kpiAchieved: [] },
  },
  {
    id: "monthly-2026-10",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 10,
    status: "draft",
    weeklyGoals: [],
    programExecutions: [],
    dailyLogIds: [],
    evaluation: { kpiAchieved: [] },
  },
  {
    id: "monthly-2026-11",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 11,
    status: "draft",
    weeklyGoals: [],
    programExecutions: [],
    dailyLogIds: [],
    evaluation: { kpiAchieved: [] },
  },
  {
    id: "monthly-2026-12",
    annualPlanId: "annual-2026",
    year: 2026,
    month: 12,
    status: "draft",
    weeklyGoals: [],
    programExecutions: [],
    dailyLogIds: [],
    evaluation: { kpiAchieved: [] },
  },
];

/** 2027년은 비어있음 (annual-2027은 status=draft라 슬롯 미생성) */
export const MOCK_MONTHLY_PLANS_2027: MonthlyPlan[] = [];